{% set name = "distro" %}
{% set version = "1.2.0" %}
{% set sha256 = "d94370e43b676ac44fbe1ab68ca903a6147eaba3a9e8eff85b2c05556a455b76" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: '{{ sha256 }}'

build:
  skip: True  # [not linux]
  number: 0
  entry_points:
    - distro = distro:main
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python

test:
  commands:
    - distro --help
  imports:
    - distro

about:
  home: https://github.com/nir0s/distro
  license: Apache-2.0
  license_file: LICENSE
  summary: Linux Distribution - a Linux OS platform information API
  doc_url: http://distro.readthedocs.io/en/latest/
  dev_url: https://github.com/nir0s/distro

extra:
  recipe-maintainers:
    - windelbouwman
    - windelbouwmanbosch
