{% set name = "distro" %}
{% set version = "1.3.0" %}
{% set sha256 = "224041cef9600e72d19ae41ba006e71c05c4dc802516da715d7fda55ba3d8742" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: '{{ sha256 }}'

build:
  number: 1001
  entry_points:
    - distro = distro:main
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  build:
    - python
    - pip
  run:
    - python

test:
  commands:
    - distro --help
  imports:
    - distro

about:
  home: https://github.com/nir0s/distro
  license: Apache-2.0
  license_file: LICENSE
  summary: Linux Distribution - a Linux OS platform information API
  doc_url: http://distro.readthedocs.io/en/latest/
  dev_url: https://github.com/nir0s/distro

extra:
  recipe-maintainers:
    - windelbouwman
    - windelbouwmanbosch
    - abloemert
