travis:
  secure:
    BINSTAR_TOKEN: tCQSyAFX1mabr5sMhrUhmXAo3qHLBbJejdeNKe5RZD5s/7TA/xBELpIEiBZUNiAK5Dkj7wJcGwPmvBaA/ovL5qeMWx7isBuF/vrlsk1CxRu9kWjFVvY6ZQyYTlGBPfrNdFGDAk4k7zsDMXez0znuB8rdwlq4r5vb26w7IA7Pj9NM4BHiiUQvyKvVWTpleq8oJo0r4J41s7dHEwd84li3a+SU/zsQperX5/BajSrBC5fbolUfW3+40MV4vGDZe46QnnUnVb0lSRQuVfeIyBR2l1Gj3HdlXzLEiEm8byALVwOEdd8g1RlwUoZ8mAg9qcxwnSBGQn4muwjIX+PmXcIXd1meHfbu1kproa+8eJKMvgo4504ke8Mgfqrd6LHQcqZ2qrThMg/f3U218bajFYufmisbBTMjXkHkMNLQOQxU4kBG7zNw2BdsnAllgcIWRh+1+zZfyR7yvCC6moq4/f++TcNh04yT+BI/dMu/lFLtzr3KTR7w8yvXhNgzf6QayXKMeljrXaWrXD66/uDL+SC5Sekpbkbm/CXRLZeLRTvolcI3teV+Kb9JTNlYZtMjTJhmpdYcKBH8oHPwUqguTiFVrHgCITX/v9lMMZdNCSJ6cJMmpAVtvc0MoosxP89dci7peEK2ifDoAZTT2BHIjnQefiNam6LbsPd0JJgK50LU4hc=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
