travis:
  secure:
    BINSTAR_TOKEN: srnQDIEsQE5LbRsfPZTXrvC+t/aCGybxKa0Xl0O0G6HfRE77jbv6FxvRdXx5+A/DMiKCVUhZ1jshIyN9pQSgflQC2FgPDoXvOIQBpYUTLEGV+CAF+GX1CK+lrqYX4DRaD1ABIfluboZ+IbuiwDDG9ySe+EDUhO5h/d4NAqZFg5soSaeyi7d/NNWdSvaToC6LxZGxpEUXw5gEvBvB1bvQd9KNF49BmdKKwOmexJqDc99TtX+6vTZ83z74k3DOHRL5wH/VZYaLnEXhXvQ2z+Hmq6zqEEJneMSnaJSM2bKPzjiel/tIAGbSW5RuxSIbZER5rmxyEoSd8HE4+qYKiuYD7NkY7ei9LuwS0OgL7IABGhYODIjWvorEPl35hnx5eqjL5RByGKv31sM2hAGiDdSiukvBS3Pq/cLmZfxVj32d3kHYpQYrVFgCgeGzdV4RfMLrwS3wAD/UD2HaXdE8OBRyTFekxBcyl57LZIRhF8muWHGVK3wO+i4/sKF0Ja6AIec11x2sosTlDZfFfiGbxSU+fHfWDjVtDQvpHazCpjVZDrYS+Q2qUWqZkA5Aytm64EqWrA0TpNYKBngff/Tt2NTVHYnvuIjjcyYLm1QG3E66hJp8cCzKQ2D3bmWqOz5G3fviCBm+6DpIP09jh+BS0v+eQcn4X5yV+j25eW37E33WZFg=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
